// react-micro-frontend/vue-micro-frontend/src/bootstrap.js
import { createApp } from 'vue'
import App from './App'

const mount = (el) => {
    const app = createApp(App)
    app.mount(el)
}

if (process.env.NODE_ENV === 'development') {
    const devRoot = document.querySelector('#vue-dev-app')
    if (devRoot) {
        mount(devRoot)
    }
}

export { mount }

// react-micro-frontend/react-micro-frontend/src/bootstrap.js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'
import { createBrowserHistory } from 'history'

const mount = (el) => {
    const history = createBrowserHistory()

    ReactDOM.render(
        <App history={history} />,
        el
    )

    return {
        onParentNavigate({ pathname: nextPathname }) {
            const { pathname } = history.location
            if (pathname !== nextPathname) {
                history.push(nextPathname)
            }
        }
    }
}

if (process.env.NODE_ENV === 'development') {
    const devRoot = document.querySelector('#react-dev-app')
    if (devRoot) {
        mount(devRoot)
    }
}

export { mount }
